
export const options = [
    { value: 'Reading', label: 'Reading' },
    { value: 'Movies', label: 'Movies' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Programming', label: 'Programming' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Poetry', label: 'Poetry' },
    { value: 'Rhetoric/Speech', label: 'Rhetorics/Speech' },
    { value: 'Music', label: 'Music' },
    { value: 'Singing', label: 'Singing' },
    { value: 'Cooking', label: 'Cooking' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'Painting', label: 'Painting' },
    { value: 'Foodie', label: 'Foodie' },
    { value: 'Driving', label: 'Driving' },
    { value: 'Traveling', label: 'Traveling' },
    { value: 'Cinematography', label: 'Cinematography' },
    { value: 'Blogging', label: 'Blogging' },
    { value: 'Vlogging', label: 'Vlogging' },
    { value: 'Journaling', label: 'Journaling' },
    { value: 'Gardening', label: 'Gardening' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Backpacking', label: 'Backpacking' },
    { value: 'Scrapbooking', label: 'Scrapbooking' },
    { value: 'Stargazing', label: 'Stargazing' },
    { value: 'Science', label: 'Science' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'Mathematics', label: 'Mathematics' },
    { value: 'Aviation', label: 'Aviation' },
    { value: 'Poker', label: 'Poker' },
    { value: 'Graphic Designing', label: 'Graphic Designing' },
    { value: 'Cartography', label: 'Cartography' },
    { value: 'Calligraphy', label: 'Calligraphy' },
    { value: 'Knitting', label: 'Knitting' },
    { value: 'Animes', label: 'Animes' },
    { value: 'TV-Series', label: 'TV-Series' },
    { value: 'Others', label: 'Others' },
  ]