
export const options = [
    { value: 'Reading', label: 'Reading' },
    { value: 'Movies', label: 'Movies' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Programming', label: 'Programming' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Rhetoric/Speech', label: 'Rhetorics/Speech' },
    { value: 'Music', label: 'Music' },
    { value: 'Singing', label: 'Singing' },
    { value: 'Cooking', label: 'Cooking' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'Painting', label: 'Painting' },
    { value: 'Traveling', label: 'Traveling' },
    { value: 'Cinematography', label: 'Cinematography' },
    { value: 'Blogging', label: 'Blogging' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Science', label: 'Science' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'Mathematics', label: 'Mathematics' },
    { value: 'Graphic Designing', label: 'Graphic Designing' },
    { value: 'Animes', label: 'Animes' },
  ]